/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StandardJudge: typeof import('./src/components/activity/StandardJudge.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    ZActivityCard: typeof import('./src/components/activity/ZActivityCard.vue')['default']
    ZActivityList: typeof import('./src/components/activity/ZActivityList.vue')['default']
    ZDisplayPerson: typeof import('./src/components/member/ZDisplayPerson.vue')['default']
    ZSelectPerson: typeof import('./src/components/form/ZSelectPerson.vue')['default']
    ZTimeJudge: typeof import('./src/components/activity/ZTimeJudge.vue')['default']
  }
}
