/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCard: typeof import('element-plus/es')['ElCard']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    ZActivityCreate: typeof import('./src/components/activity/ZActivityCreate.vue')['default']
    ZActivityDescriptions: typeof import('./src/components/activity/ZActivityDescriptions.vue')['default']
    ZActivityDetails: typeof import('./src/components/activity/ZActivityDetails.vue')['default']
    ZActivityHistory: typeof import('./src/components/activity/ZActivityHistory.vue')['default']
    ZActivityImpressionDrawer: typeof import('./src/components/activity/ZActivityImpressionDrawer.vue')['default']
    ZActivityImpressionManager: typeof import('./src/components/activity/ZActivityImpressionManager.vue')['default']
    ZActivityList: typeof import('./src/components/activity/ZActivityList.vue')['default']
    ZActivityMember: typeof import('./src/components/activity/ZActivityMember.vue')['default']
    ZActivityRegisterCard: typeof import('./src/components/activity/ZActivityRegisterCard.vue')['default']
    ZActivityStatus: typeof import('./src/components/tags/ZActivityStatus.vue')['default']
    ZActivityType: typeof import('./src/components/tags/ZActivityType.vue')['default']
    ZButtonOrCard: typeof import('./src/components/utils/ZButtonOrCard.vue')['default']
    ZDisplayPerson: typeof import('./src/components/member/ZDisplayPerson.vue')['default']
    ZSelectLanguage: typeof import('./src/components/form/ZSelectLanguage.vue')['default']
    ZSelectPerson: typeof import('./src/components/form/ZSelectPerson.vue')['default']
    ZTimeJudge: typeof import('./src/components/activity/ZTimeJudge.vue')['default']
    ZVerticalNav: typeof import('./src/components/form/ZVerticalNav.vue')['default']
  }
}
