/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElEmpty: (typeof import('element-plus/es'))['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElTag: typeof import('element-plus/es')['ElTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZActivityCard: typeof import('./src/components/activity/ZActivityCard.vue')['default']
    ZActivityCreate: typeof import('./src/components/activity/ZActivityCreate.vue')['default']
    ZActivityDetails: typeof import('./src/components/activity/ZActivityDetails.vue')['default']
    ZActivityDuration: typeof import('./src/components/tags/ZActivityDuration.vue')['default']
    ZActivityList: typeof import('./src/components/activity/ZActivityList.vue')['default']
    ZActivityMember: typeof import('./src/components/activity/ZActivityMember.vue')['default']
    ZActivityMemberList: typeof import('./src/components/activity/ZActivityMemberList.vue')['default']
    ZActivityMerge: typeof import('./src/components/activity/ZActivityMerge.vue')['default']
    ZActivityMode: typeof import('./src/components/tags/ZActivityMode.vue')['default']
    ZActivityPage: typeof import('./src/components/activity/ZActivityPage.vue')['default']
    ZActivityStatus: typeof import('./src/components/tags/ZActivityStatus.vue')['default']
    ZActivityTag: typeof import('./src/components/tags/ZActivityTag.vue')['default']
    ZActivityType: typeof import('./src/components/tags/ZActivityType.vue')['default']
    ZAdvancedTable: typeof import('./src/components/utils/ZAdvancedTable.vue')['default']
    ZButtonOrCard: typeof import('./src/components/utils/ZButtonOrCard.vue')['default']
    ZButtonTag: typeof import('./src/components/utils/ZButtonTag.vue')['default']
    ZDataExport: typeof import('./src/components/utils/ZDataExport.vue')['default']
    ZDisplayPerson: typeof import('./src/components/member/ZDisplayPerson.vue')['default']
    ZGroupList: typeof import('./src/components/group/ZGroupList.vue')['default']
    ZGroupTimeStatistics: typeof import('./src/components/group/ZGroupTimeStatistics.vue')['default']
    ZGroupUserList: typeof import('./src/components/group/ZGroupUserList.vue')['default']
    ZGroupUserTimeList: typeof import('./src/components/group/ZGroupUserTimeList.vue')['default']
    ZInputDuration: typeof import('./src/components/form/ZInputDuration.vue')['default']
    ZLogCard: typeof import('./src/components/log/ZLogCard.vue')['default']
    ZLogList: typeof import('./src/components/log/ZLogList.vue')['default']
    ZSelectActivityMode: typeof import('./src/components/form/ZSelectActivityMode.vue')['default']
    ZSelectClass: typeof import('./src/components/form/ZSelectClass.vue')['default']
    ZSelectLanguage: typeof import('./src/components/form/ZSelectLanguage.vue')['default']
    ZSelectPerson: typeof import('./src/components/form/ZSelectPerson.vue')['default']
    ZSpecialActivityClassify: typeof import('./src/components/tags/ZSpecialActivityClassify.vue')['default']
    ZTime: typeof import('./src/components/tags/ZTime.vue')['default']
    ZTimeJudge: typeof import('./src/components/activity/ZTimeJudge.vue')['default']
    ZUploadFile: typeof import('./src/components/activity/ZUploadFile.vue')['default']
    ZUserGroup: typeof import('./src/components/tags/ZUserGroup.vue')['default']
    ZUserModification: typeof import('./src/components/group/ZUserModification.vue')['default']
    ZUserPage: typeof import('./src/components/group/ZUserPage.vue')['default']
    ZUserPosition: typeof import('./src/components/tags/ZUserPosition.vue')['default']
    ZUserTimeJudge: typeof import('./src/components/activity/ZUserTimeJudge.vue')['default']
    ZVerticalNav: typeof import('./src/components/form/ZVerticalNav.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
